Bump version to 3.22.0
AnacondaRecipes/conda-build-feedstock pull request #18
Opened 2022-08-17 19:31 UTC by kenodegard

Bumps version for conda-build 3.22.0 release.

#17 used my fork and didn't appear to trigger Prefect workflows, trying without fork.

2022-08-19 07:42 UTC, katietz requested changes
Hmm, it is ok.  this alphabetic sorting is a lot of noise.  The only thing I am a bit curious about is why 'patch'/'m2-patch' is now part of "run:" section? also its dependency there to pip feels strange. But setuptools got removed from list, but get actually indirectly pulled in via the pip dependency .... actually we should then add setuptools, and wheels too.
Please clarify if the dependency of setuptools/pip/wheel and patch is really intended and needed

2022-08-19 18:19 UTC, marcoesters commented
> @katietz Sorted dependencies since the [conda-build canary recipe](https://github.com/conda/conda-build/blob/6a1cea0111f53417aeb631aa54d7cc26d26d6628/conda.recipe/meta.yaml#L26-L54) and [conda-forge's recipe](https://github.com/conda-forge/conda-build-feedstock/blob/3c40adf342c0aa134234987ed2a1520438819aea/recipe/meta.yaml#L34-L58) (roughly) sort theirs. Made it easier to compare. I can revert if desired.
> 
> `patch`/`m2-patch` are now hard runtime dependencies, see [conda/conda-build#4495](https://github.com/conda/conda-build/pull/4495).
> 
> Added `pip` as Prefect workflow fails otherwise, no idea why.

The tests run `test_bdist_conda_setup.py`, which requires `pip` to run. Prefect cannot find the `pip` module if it's not added to the run dependencies.

2022-08-19 22:21 UTC, kenodegard commented
@marcoesters does that mean it can be moved to the test dependencies instead?

2022-08-19 22:28 UTC, marcoesters commented
> @marcoesters does that mean it can be moved to the test dependencies instead?

You could give that a try - if this builds, I think that would address some of Kai's concerns.

2022-08-22 07:43 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - wheel
It seems like `setuptools` should be in `host` too, see https://github.com/conda/conda-build/blob/cc6c050ee3325e6957dbf60f74dbe79d78d26a8f/setup.py#L4

2022-08-22 07:43 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - tqdm
Do we need `toml` in `run`? See https://github.com/conda/conda-build/blob/cc6c050ee3325e6957dbf60f74dbe79d78d26a8f/setup.py#L21
And `psutils`, see https://github.com/conda/conda-build/blob/cc6c050ee3325e6957dbf60f74dbe79d78d26a8f/setup.py#L23

2022-08-22 07:43 UTC, skupr-anaconda commented on recipe/meta.yaml
>  package:
Skip building for `py<36`, see https://github.com/conda/conda-build/blob/cc6c050ee3325e6957dbf60f74dbe79d78d26a8f/setup.py#L56

2022-08-22 07:43 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - chardet
Is `cctools` missing for `osx` or we do not need it? See https://github.com/conda-forge/conda-build-feedstock/commit/a5f4308faddf3ebd122f89db3903081780ac7be9

2022-08-22 07:43 UTC, skupr-anaconda commented on recipe/meta.yaml
>      - test_bdist_conda_setup.py
Is it ok to add in test/imports? :
       - conda_build.cli
       - conda_build.skeletons
       - conda_build.os_utils
       - conda_build.jinja_context
See https://github.com/conda/conda-build/blob/cc6c050ee3325e6957dbf60f74dbe79d78d26a8f/setup.py#L61-L63 and https://github.com/conda-forge/conda-build-feedstock/blob/3c40adf342c0aa134234987ed2a1520438819aea/recipe/meta.yaml#L76

2022-08-22 18:13 UTC, kenodegard commented on recipe/meta.yaml
> +    - tqdm
`toml` added

`psutil` is already included, see line 49

2022-08-23 05:35 UTC, skupr-anaconda approved these changes

2022-08-23 15:55 UTC, katietz approved these changes
well, I am still not happy to add all python standard build tools by default to conda-build, as this can cause issue on bootstrapping as we could see then these cyclic dependency issues.
Anyway if upstream goes that route, we should follow here

2022-08-23 19:47 UTC, merged